### PR TITLE
Founder Story: Anton Bryzgalov, Ethereum to S3

### PR DESCRIPTION
**Pull request by bryzgaloff**
A short summary of my blogpost on Medium: https://betterprogramming.pub/how-to-dump-full-ethereum-history-to-s3-296fb3ad175

Exclusively for Data Engineering Weekly.

Looking forward to being posted! :) Thank you guys for doing a great job and allowing us to spread the data engineering knowledge 🤝

### CODE REVIEW

**Comment by bryzgaloff** [comment]
Hi @ananthdurai! Any assistance required from my side to give this newsletter a go? :)

**Comment by ananthdurai** [comment]
This looks awesome. Thank you, let me add this week’s edition.

**Comment by bryzgaloff** [comment]
Hi @ananthdurai! Noted the article on DE weekly: https://www.dataengineeringweekly.com/i/81592223/anton-bryzgalov-how-to-export-a-full-history-of-ethereum-blockchain-to-s

Though I have contributed this as a Data Founder story since this is an **exclusive** summary for DE Data Founder Edition. Will you distribute it as a Data Founder Story too?

**Comment by ananthdurai** [comment]
Hi @bryzgalof, we feature the founder's story about why someone started a startup and their personal journey. The post is mainly centered around technical content.

**Comment by bryzgaloff** [comment]
Hi @ananthdurai may I expect any response from you regarding my latest comment? Thank you in advance!

https://github.com/ananthdurai/dataengineeringweekly/pull/31#issuecomment-1296843601

**Pull request merged**
